const express = require("express");
const cors = require("cors");
const mongoose = require('mongoose');
const SpotifyWebAPI = require('spotify-web-api-node'); // added 
require('dotenv').config();  // Loads .env file

const app = express();
const PORT = process.env.PORT || 5000; // added

// Connect to MongoDB
mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
})
  .then(() => console.log('Connected to MongoDB'))
  .catch((err) => console.error('MongoDB connection error:', err));

// Feedback schema
const feedbackSchema = new mongoose.Schema({
  userId: String, // Spotify user ID or custom ID
  playlistTracks: [String],
  rating: Number,
  mood: String,
  time: String,
  focusLevel: Number,
  timestamp: { type: Date, default: Date.now },
});
const Feedback = mongoose.model('Feedback', feedbackSchema);

app.use(cors());
app.use(express.json());

const spotifyAPI = new SpotifyWebAPI({
  clientId: process.env.SPOTIFY_CLIENT_ID,
  clientSecret: process.env.SPOTIFY_CLIENT_SECRET,
  redirectUri: process.env.SPOTIFY_REDIRECT_URI,
});

// Basic route to test server
app.get("/", (req, res) => {
  res.send("Backend running");
});

// TODO: Add routes for Spotify API and database interactions
// Spotify login
app.get('/spotify-login', (req, res) => {
  const scopes = [
    'user-read-private',
    'user-read-email',
    'playlist-read-private',
    'playlist-modify-public',
    'playlist-modify-private',
  ];
  const authorizeURL = spotifyApi.createAuthorizeURL(scopes);
  res.json({ url: authorizeURL });
});

// Spotify callback
app.get('/callback', async (req, res) => {
  const { code } = req.query;
  try {
    const data = await spotifyApi.authorizationCodeGrant(code);
    const { access_token, refresh_token } = data.body;
    res.redirect(`http://192.168.56.1:3000?access_token=${access_token}`);
  } catch (err) {
    res.status(500).send('Auth error');
  }
});

// Get playlist recommendations
app.post('/recommendations', async (req, res) => {
  const { mood, time, focusLevel, accessToken } = req.body;
  spotifyApi.setAccessToken(accessToken);
  try {
    // Map inputs to Spotify parameters
    const moodGenres = {
      calm: 'ambient,chill,acoustic',
      upbeat: 'pop,rock,dance',
      focused: 'classical,lo-fi',
      energetic: 'edm,hip-hop',
    };
    const timeEnergy = {
      morning: 0.7,
      afternoon: 0.5,
      evening: 0.3,
      night: 0.2,
    };
    const genres = moodGenres[mood] || 'pop';
    const energy = Math.min(timeEnergy[time] || 0.5, focusLevel / 10);
    const recommendations = await spotifyApi.getRecommendations({
      seed_genres: genres,
      target_energy: energy,
      target_valence: mood === 'upbeat' || mood === 'energetic' ? 0.8 : 0.4, // Valence for mood
      limit: 20,
    });
    res.json(recommendations.body.tracks);
  } catch (err) {
    res.status(500).send('Error fetching recommendations');
  }
});

// Create playlist (optional)
app.post('/create-playlist', async (req, res) => {
  const { accessToken, trackUris, userId } = req.body;
  spotifyApi.setAccessToken(accessToken);
  try {
    const playlist = await spotifyApi.createPlaylist(userId, 'Study Playlist', {
      public: false,
      description: 'Generated by Study Playlist Recommender',
    });
    await spotifyApi.addTracksToPlaylist(playlist.body.id, trackUris);
    res.json({ playlistUrl: playlist.body.external_urls.spotify });
  } catch (err) {
    res.status(500).send('Error creating playlist');
  }
});

// Save user feedback
app.post('/feedback', async (req, res) => {
  const { userId, playlistTracks, rating, mood, time, focusLevel } = req.body;
  try {
    await db.collection('feedback').add({
      userId,
      playlistTracks, // Array of track IDs
      rating: Number(rating),
      mood,
      time,
      focusLevel: Number(focusLevel),
      timestamp: admin.firestore.FieldValue.serverTimestamp(),
    });
    res.send('Feedback saved');
  } catch (err) {
    res.status(500).send('Error saving feedback');
  }
});

// const PORT = 5000;
// app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
